apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: <secret-name>
  namespace: <namespace>
spec:
  encryptedData:
    API_KEY: "<sealed by seal.sh>"
  template:
    metadata:
      name: <secret-name>
      namespace: <namespace>
    type: Opaque
