apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: <registry-pull-secret>
  namespace: <namespace>
spec:
  encryptedData:
    .dockerconfigjson: "<sealed by seal.sh>"
  template:
    metadata:
      name: <registry-pull-secret>
      namespace: <namespace>
    type: kubernetes.io/dockerconfigjson
