apiVersion: v1
kind: ServiceAccount
metadata:
  name: factory
  namespace: "{{NS_FACTORY}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{PROJECT_NAME}}-factory-auth"
rules:
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{PROJECT_NAME}}-factory-auth"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{PROJECT_NAME}}-factory-auth"
subjects:
  - kind: ServiceAccount
    name: factory
    namespace: "{{NS_FACTORY}}"
