apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: <secret-name>
  namespace: <namespace>
  labels:
    app.kubernetes.io/name: <app-name>
    app.kubernetes.io/part-of: <project-name>
    app.kubernetes.io/component: application
spec:
  encryptedData:
    API_KEY: <sealed by seal.sh>
  template:
    metadata:
      name: <secret-name>
      namespace: <namespace>
    type: Opaque
