apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{MCP_SERVICE_NAME}}"
  namespace: "{{NS_MCP}}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{PROJECT_NAME}}-mcp-{{MCP_NAME}}-tokenreview"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aa-mcp-tokenreview
subjects:
  - {kind: ServiceAccount, name: "{{MCP_SERVICE_NAME}}", namespace: "{{NS_MCP}}"}
