# Chart 2.20.0, controller 0.40.0. Full explicit release values.
fullnameOverride: sealed-secrets-controller
image:
  tag: "0.40.0@sha256:b1ff382e9300dc9e74991f3177b18cafc06ce43b5c21349c86adbdd1d1c177d3"
nodeSelector:
  "{{LABEL_PREFIX}}/role-control-plane": "true"
service:
  type: ClusterIP
