apiVersion: v1
kind: Config
clusters:
  - name: "{{PROJECT_NAME}}"
    cluster:
      server: "{{APISERVER_URL}}"
      certificate-authority-data: <cluster-ca-base64>
contexts:
  - name: "{{PROJECT_NAME}}"
    context:
      cluster: "{{PROJECT_NAME}}"
      user: oidc
current-context: "{{PROJECT_NAME}}"
users:
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        command: kubectl
        interactiveMode: IfAvailable
        args:
          - oidc-login
          - get-token
          - "--oidc-issuer-url={{OIDC_ISSUER_URL}}"
          - "--oidc-client-id={{OIDC_CLIENT_ID}}"
          - --oidc-extra-scope=groups
