apiVersion: v1
kind: ServiceAccount
metadata:
  name: panel
  namespace: '{{NS_PORTAL}}'
  labels:
    app.kubernetes.io/name: panel
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
    app.kubernetes.io/component: portal
automountServiceAccountToken: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: panel-data
  namespace: '{{NS_PORTAL}}'
  labels:
    app.kubernetes.io/name: panel-data
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
    app.kubernetes.io/component: portal
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: '{{STORAGE_CLASS_DEFAULT}}'
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: panel
  namespace: '{{NS_PORTAL}}'
  labels:
    app.kubernetes.io/name: panel
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
    app.kubernetes.io/component: portal
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: panel
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: internal
    port: 8081
    targetPort: 8081
