"""Generate a REPOS.md-style map (purpose, dependency edges, blast radius, cycles, pin drift) from
an index, and diff it against a hand-written map such as <optional-map>/REPOS.md.

Edges are measured, not copied: declared in package.json AND/OR seen in resolved imports,
labelled runtime / test / tooling. A cycle is reported as test-only when removing test and
tooling edges breaks it (docs/FACTORY-DESIGN.md: both "known cycles" are test-only on one side).
"""
from __future__ import annotations

import json
import re
from collections import defaultdict
from pathlib import Path

from . import graph, queries
from .resolve import INTERNAL_SCOPE


def _short_names(conn) -> dict[str, str]:
    out = {r["name"]: r["short"] for r in conn.execute("SELECT name, short FROM repos")}
    for d in conn.execute("SELECT dep, target_repo FROM pkg_deps WHERE internal=1 AND target_repo IS NOT NULL"):
        if d["target_repo"] not in out and d["dep"].startswith(INTERNAL_SCOPE):
            out[d["target_repo"]] = d["dep"][len(INTERNAL_SCOPE):]
    return out


def measured(conn) -> dict:
    g = queries.repo_graph(conn)
    short = _short_names(conn)
    present = set(g["nodes"])
    blast = {}
    for r in g["nodes"]:
        run, test_only = graph.blast(r, g["all"], g["runtime"])
        blast[r] = {"runtime": sorted(run), "test_only": test_only}
    cycles = []
    nodes = sorted(present | {b for bs in g["all"].values() for b in bs})
    for comp in graph.tarjan_scc(nodes, g["all"]):
        sub = {a: g["runtime"].get(a, set()) & set(comp) for a in comp}
        legs = [(a, b, g["edges"][(a, b)]) for a in comp for b in comp if b in g["all"].get(a, ())]
        cycles.append({"repos": comp, "runtime_cycle": bool(graph.tarjan_scc(comp, sub)), "legs": legs})
    return {"graph": g, "short": short, "present": present, "blast": blast, "cycles": cycles}


def _risk(n_runtime: int, total_repos: int) -> str:
    if n_runtime >= max(3, total_repos // 2):
        return "HIGH"
    if n_runtime >= 1:
        return "MEDIUM"
    return "LOW"


def _test_only_evidence(conn, a: str, b: str, limit: int = 3) -> list[str]:
    rows = conn.execute("""SELECT DISTINCT f.path FROM imports i JOIN files f ON f.id=i.file_id
                           JOIN repos r ON r.id=i.repo_id WHERE r.name=? AND i.target_repo=? AND i.edge!='runtime'
                           ORDER BY f.path LIMIT ?""", (a, b, limit)).fetchall()
    return [r["path"] for r in rows]


def generate(conn, compare_path: str | Path | None = None) -> str:
    m = measured(conn)
    g, short, present = m["graph"], m["short"], m["present"]
    meta = {k: v for k, v in conn.execute("SELECT key, value FROM meta")}
    counts = json.loads(meta.get("counts", "{}"))
    S = lambda r: short.get(r, r)   # noqa: E731
    L: list[str] = []
    L.append(f"# Estate map (generated): snapshot {meta.get('snapshot_id')}")
    L.append("")
    L.append(f"Generated by `factory/index` from snapshot `{meta.get('snapshot_id')}` at {meta.get('built_at')} "
             f"({counts.get('repos')} repos, {counts.get('code_files')} code files, {counts.get('symbols')} symbols; "
             f"tokens: {meta.get('counted_by')}). Edges are measured from package.json and resolved imports, "
             "not copied. Do not edit; regenerate with `python -m estate_index repos-md`.")
    L.append("")
    L.append("## Repos")
    L.append("")
    L.append("| Repo (dir) | Package | Responsibility | Code files | Symbols | Exported fns | Test files | "
             "Exported fns no test references (+ only module imported by a test) | jest |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    stats = {r["name"]: r for r in conn.execute("""
        SELECT r.name, r.package, r.description, r.code_files, r.test_files, r.has_jest,
          (SELECT count(*) FROM symbols s WHERE s.repo_id=r.id) AS n_sym,
          (SELECT count(*) FROM symbols s JOIN files f ON f.id=s.file_id WHERE s.repo_id=r.id AND s.exported=1
             AND s.kind IN ('function','method') AND f.role='src') AS n_exp,
          (SELECT count(*) FROM symbols s JOIN files f ON f.id=s.file_id JOIN symbol_stats st ON st.symbol_id=s.id
             WHERE s.repo_id=r.id AND s.exported=1 AND s.kind IN ('function','method') AND f.role='src'
             AND st.test_level='none') AS n_untested,
          (SELECT count(*) FROM symbols s JOIN files f ON f.id=s.file_id JOIN symbol_stats st ON st.symbol_id=s.id
             WHERE s.repo_id=r.id AND s.exported=1 AND s.kind IN ('function','method') AND f.role='src'
             AND st.test_level='module') AS n_module
        FROM repos r ORDER BY r.name""")}
    for r in sorted(stats.values(), key=lambda r: r["name"]):
        L.append(f"| `{r['name']}` | `{r['package'] or '-'}` | {(r['description'] or '').replace('|', '/')} | "
                 f"{r['code_files']} | {r['n_sym']} | {r['n_exp']} | {r['test_files']} | {r['n_untested']} (+{r['n_module']}) | "
                 f"{'yes' if r['has_jest'] else 'NO'} |")
    missing = sorted({b for bs in g["all"].values() for b in bs} - present)
    if missing:
        L.append("")
        L.append("Referenced but not in this snapshot (edges known from package.json only): "
                 + ", ".join(f"`{x}`" for x in missing))
    L.append("")
    L.append("## Dependency edges (X depends on -> Y)")
    L.append("")
    L.append("```")
    width = max((len(S(a)) for a in g["all"]), default=8)
    for a in sorted(g["all"], key=S):
        parts = []
        for b in sorted(g["all"][a], key=S):
            e = g["edges"][(a, b)]
            tag = "" if e["kind"] == "runtime" else f" ({e['kind'].replace('declared_only', 'declared, unused')})"
            parts.append(S(b) + ("*" if b not in present else "") + tag)
        L.append(f"{S(a):<{width}} -> {', '.join(parts)}")
    L.append("```")
    L.append("`*` = not in this snapshot. `(test)` / `(tooling)` = only test or config/script files import it. "
             "`(declared, unused)` = in package.json, no import found.")
    L.append("")
    L.append("| From | To | package.json | Runtime imports | Test imports | Tooling imports | Kind |")
    L.append("|---|---|---|---|---|---|---|")
    for (a, b), e in sorted(g["edges"].items(), key=lambda kv: (S(kv[0][0]), S(kv[0][1]))):
        L.append(f"| {S(a)} | {S(b)} | {e['declared_section'] or '-'} | {e['runtime_imports']} | {e['test_imports']} "
                 f"| {e['tooling_imports']} | {e['kind']} |")
    L.append("")
    L.append("## Blast radius: change X, then build/test these")
    L.append("")
    L.append("| Change in... | Must re-verify (runtime, transitive) | Test-only dependents | Risk |")
    L.append("|---|---|---|---|")
    order = sorted(m["blast"].items(), key=lambda kv: (-len(kv[1]["runtime"]), kv[0]))
    for r, b in order:
        run = ", ".join(S(x) for x in b["runtime"]) or "nothing depends on it"
        to = ", ".join(S(x) for x in b["test_only"]) or "-"
        L.append(f"| `{r}` ({S(r)}) | {run} | {to} | {_risk(len(b['runtime']), len(present))} |")
    L.append("")
    L.append("Risk: HIGH = at least 3 (or half the snapshot) runtime dependents, MEDIUM = 1-2, LOW = none. "
             "Within this snapshot only.")
    L.append("")
    L.append("## Cycles")
    L.append("")
    if not m["cycles"]:
        L.append("None.")
    for c in m["cycles"]:
        legs = []
        for a, b, e in c["legs"]:
            ev = ""
            if e["kind"] != "runtime":
                files = _test_only_evidence(conn, a, b)
                ev = f" via {', '.join(files)}" if files else ""
            legs.append(f"{S(a)}->{S(b)} ({e['kind']}{ev})")
        verdict = "RUNTIME cycle" if c["runtime_cycle"] else "not a runtime cycle (test/tooling-only on one side)"
        L.append(f"- `{' <-> '.join(S(x) for x in c['repos'])}`: {verdict}. " + "; ".join(legs))
    L.append("")
    L.append("## Pin drift (consumers pin a tag; tests here run against sibling HEAD)")
    L.append("")
    rows = conn.execute("""SELECT r.name AS consumer, d.dep, d.pin_ref, d.target_repo, d.commits_past_pin,
                           d.files_changed FROM pkg_deps d JOIN repos r ON r.id=d.repo_id
                           WHERE d.package_dir='' AND d.internal=1 AND d.pin_ref IS NOT NULL
                           ORDER BY d.target_repo, r.name""").fetchall()
    if rows:
        L.append("| Target | Pinned as | Consumers | HEAD past pin |")
        L.append("|---|---|---|---|")
        grouped: dict[tuple, list[str]] = defaultdict(list)
        for d in rows:
            grouped[(d["target_repo"], d["dep"], d["pin_ref"], d["commits_past_pin"], d["files_changed"])].append(
                S(d["consumer"]))
        for (t, dep, ref, n, nf), cons in sorted(grouped.items(), key=lambda kv: (-(kv[0][3] or 0), kv[0][0])):
            past = f"{n} commit(s), {nf} file(s)" if n is not None else "unknown (not in snapshot)"
            L.append(f"| {S(t)} | `{dep}#{ref}` | {', '.join(cons)} | {past} |")
    else:
        L.append("No MANIFEST pins (snapshot built without aa's MANIFEST.json).")
    L.append("")
    L.append("## Most-depended-on cross-repo modules")
    L.append("")
    L.append("| Module | Dependent files | Consumer repos | Names imported |")
    L.append("|---|---|---|---|")
    top = conn.execute("""SELECT tr.name AS repo, tf.path, count(DISTINCT i.file_id) AS n,
                          group_concat(DISTINCT cr.name) AS consumers
                          FROM imports i JOIN files tf ON tf.id=i.target_file_id JOIN repos tr ON tr.id=tf.repo_id
                          JOIN repos cr ON cr.id=i.repo_id WHERE cr.id != tr.id
                          GROUP BY tf.id ORDER BY n DESC, tf.path LIMIT 12""").fetchall()
    for t in top:
        names = conn.execute("""SELECT n.imported, count(*) c FROM import_names n JOIN imports i ON i.id=n.import_id
                                JOIN files tf ON tf.id=i.target_file_id JOIN repos tr ON tr.id=tf.repo_id
                                WHERE tr.name=? AND tf.path=? AND i.repo_id != tr.id GROUP BY 1 ORDER BY 2 DESC
                                LIMIT 6""", (t["repo"], t["path"])).fetchall()
        L.append(f"| `{S(t['repo'])}/{t['path']}` | {t['n']} | "
                 f"{', '.join(S(x) for x in sorted((t['consumers'] or '').split(',')))} | "
                 f"{', '.join(n['imported'] for n in names)} |")
    if compare_path:
        L.append("")
        L.extend(diff_section(m, compare_path))
    L.append("")
    return "\n".join(L)


_EDGE_LINE = re.compile(r"^\s*([A-Za-z0-9._-]+)\s*->\s*(.*)$")
_CYCLE_LINE = re.compile(r"`([A-Za-z0-9._-]+)\s*(?:<->|â†”)\s*([A-Za-z0-9._-]+)`")


def parse_hand_written(text: str) -> dict:
    """Edges and cycles from a hand-written REPOS.md (the `X -> a, b` code block and the cycles list)."""
    edges: dict[str, set[str]] = defaultdict(set)
    in_block = False
    cur = None
    section = ""
    for line in text.splitlines():
        if line.startswith("#"):
            section = line.lower()
        if line.strip().startswith("```"):
            in_block = not in_block
            cur = None
            continue
        if in_block and "depend" in section:
            mm = _EDGE_LINE.match(line)
            if mm:
                cur = mm.group(1)
                rest = mm.group(2)
            elif cur and line.startswith(" "):
                rest = line
            else:
                continue
            for tok in re.split(r"[,\s]+", re.sub(r"\(.*?\)", "", rest)):
                if tok:
                    edges[cur].add(tok)
    cycles = [tuple(sorted(c)) for c in _CYCLE_LINE.findall(text)]
    return {"edges": edges, "cycles": cycles}


def diff_section(m: dict, compare_path: str | Path) -> list[str]:
    p = Path(compare_path).expanduser()
    L = [f"## Diff against `{p}`", ""]
    try:
        hw = parse_hand_written(p.read_text(encoding="utf-8"))
    except OSError as exc:
        return L + [f"Could not read it: {exc}"]
    g, short = m["graph"], m["short"]
    present_short = {short.get(r, r) for r in m["present"]}
    mine = {(short.get(a, a), short.get(b, b)): e for (a, b), e in g["edges"].items()}
    theirs = {(a, b) for a, bs in hw["edges"].items() for b in bs}
    only_hw = sorted((a, b) for a, b in theirs if a in present_short and (a, b) not in mine)
    only_me = sorted((a, b) for a, b in mine if (a, b) not in theirs)
    nonrt = sorted((a, b, e["kind"]) for (a, b), e in mine.items() if (a, b) in theirs and e["kind"] != "runtime")
    L.append(f"Compared for the {len(present_short)} repos in this snapshot "
             f"({', '.join(sorted(present_short))}); edges from repos outside it are not checked.")
    L.append("")
    L.append("- Edges in the hand-written map but not found here: "
             + (", ".join(f"{a}->{b}" for a, b in only_hw) or "none"))
    L.append("- Edges found here but missing from the hand-written map: "
             + (", ".join(f"{a}->{b} ({mine[(a, b)]['kind']})" for a, b in only_me) or "none"))
    L.append("- Edges the hand-written map lists that are not runtime here: "
             + (", ".join(f"{a}->{b} ({k})" for a, b, k in nonrt) or "none"))
    measured_cycles = {tuple(sorted(short.get(x, x) for x in c["repos"])): c for c in m["cycles"]}
    for c in hw["cycles"]:
        if not set(c) <= present_short:
            L.append(f"- Cycle `{' <-> '.join(c)}`: not checkable (not all repos in this snapshot)")
            continue
        mc = next((v for k, v in measured_cycles.items() if set(c) <= set(k)), None)
        if mc is None:
            L.append(f"- Cycle `{' <-> '.join(c)}`: NOT found in the measured graph")
        elif mc["runtime_cycle"]:
            L.append(f"- Cycle `{' <-> '.join(c)}`: confirmed, runtime on both sides")
        else:
            L.append(f"- Cycle `{' <-> '.join(c)}`: only test/tooling on one side (not a runtime cycle)")
    return L
