apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{PROJECT_NAME}}-40-sessions-platform'
  labels:
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
    app.kubernetes.io/component: cluster
  namespace: '{{NS_ARGOCD}}'
  annotations:
    argocd.argoproj.io/sync-wave: '40'
spec:
  project: platform-policy
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{NS_SYSTEM}}'
  sources:
  - repoURL: '{{ORG_GIT_REMOTE}}'
    targetRevision: '{{GIT_REVISION}}'
    path: rendered/global/sessions/k8s
    directory:
      recurse: true
      include: '*.yaml'
  syncPolicy:
    syncOptions:
    - FailOnSharedResource=true
    - PruneLast=true
