apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-cred
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-key
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
