apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: "{{PROJECT_NAME}}-wazuh"
$patch: delete
