apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: headlamp-ingress
  namespace: '{{NS_PORTAL}}'
  labels:
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
    app.kubernetes.io/component: headlamp
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: headlamp
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: cloudflared
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: oauth2-proxy-headlamp
    ports:
    - protocol: TCP
      port: 4466
