apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: litellm
  namespace: '{{NS_MONITORING}}'
  labels:
    app.kubernetes.io/part-of: '{{PROJECT_NAME}}'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: litellm
  namespaceSelector:
    matchNames:
    - '{{NS_LLM}}'
  endpoints:
  - port: metrics
    path: /metrics/
    interval: 30s
    honorLabels: true
