apiVersion: v1
kind: LimitRange
metadata:
  name: ci-defaults
  namespace: {{PROJECT_NAME}}-arc-runners
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 250m
      memory: 512Mi
      ephemeral-storage: 1Gi
    default:
      cpu: '2'
      memory: 4Gi
      ephemeral-storage: 20Gi
    max:
      cpu: '2'
      memory: 4Gi
      ephemeral-storage: 20Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ci-quota
  namespace: {{PROJECT_NAME}}-arc-runners
spec:
  hard:
    pods: '12'
    requests.cpu: '3'
    requests.memory: 6Gi
    requests.ephemeral-storage: 12Gi
    limits.cpu: '24'
    limits.memory: 48Gi
    limits.ephemeral-storage: 240Gi
